# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', models.FloatField()),
                ('ohms_per_m_min', models.FloatField()),
                ('ohms_per_m_rated', models.FloatField()),
                ('ohms_per_m_max', models.FloatField()),
                ('standard', models.CharField(max_length=1)),
                ('tolerance', models.FloatField()),
                ('mass', models.FloatField()),
                ('grade_1_dia_min', models.FloatField()),
                ('grade_1_dia_max', models.FloatField()),
                ('grade_2_dia_min', models.FloatField()),
                ('grade_2_dia_max', models.FloatField()),
            ],
        ),
    ]
