# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wire',
            name='area',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
