# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactor', '0002_wire_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laminations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_A', models.FloatField()),
                ('measure_B', models.FloatField()),
                ('measure_C', models.FloatField()),
                ('measure_D', models.FloatField()),
                ('measure_E', models.FloatField()),
                ('measure_F', models.FloatField()),
                ('measure_G', models.FloatField()),
                ('path_length', models.FloatField()),
                ('window_area', models.FloatField()),
            ],
        ),
    ]
