# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactor', '0003_laminations'),
    ]

    operations = [
        migrations.AddField(
            model_name='laminations',
            name='lam_size',
            field=models.CharField(default='0', max_length=20),
            preserve_default=False,
        ),
    ]
