# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactor', '0005_auto_20161207_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bobbin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
                ('us_name', models.CharField(max_length=20)),
                ('section_type', models.CharField(max_length=20)),
                ('terminals', models.CharField(max_length=20)),
                ('measure_A', models.FloatField()),
                ('measure_B', models.FloatField()),
                ('measure_C', models.FloatField()),
                ('measure_D', models.FloatField()),
                ('measure_E', models.FloatField()),
                ('measure_F', models.FloatField()),
                ('measure_G', models.FloatField()),
                ('measure_H', models.FloatField()),
                ('measure_J', models.FloatField()),
                ('measure_K', models.FloatField()),
                ('measure_L', models.FloatField()),
                ('measure_M', models.FloatField()),
                ('measure_N', models.FloatField()),
                ('measure_P', models.FloatField()),
                ('core_material', models.CharField(max_length=20)),
                ('frame_va', models.FloatField()),
                ('mp_part_number', models.CharField(max_length=20)),
            ],
        ),
    ]
